name: prueba de codigo

on:
  pull request:

jobs:
  probar-seguridad:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: accion
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint